# Project-wide Gradle settings.

# Gradle JVM memory
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true

# Gradle Configuration Cache
org.gradle.configuration-cache=true

# Limit Gradle workers to reduce RAM usage
org.gradle.workers.max=2

# Kotlin incremental compilation
kotlin.incremental=true